In [1]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt
dataset = load_dataset('lukebarousse/data_jobs')
df=dataset['train'].to_pandas()
df['job_posted_date']=pd.to_datetime(df['job_posted_date'])

In [ ]:
# task NAN value change for medium values, 
# remove duplicates#
#fillna, drop_duplicates

In [2]:
df.loc[:10,'salary_year_avg':'salary_hour_avg']

    salary_year_avg  salary_hour_avg
0               NaN              NaN
1               NaN              NaN
2               NaN              NaN
3               NaN              NaN
4               NaN              NaN
5               NaN              NaN
6               NaN              NaN
7               NaN              NaN
8               NaN              NaN
9               NaN              NaN
10              NaN              NaN

In [5]:
median_salary_year=df['salary_year_avg'].median()

In [6]:
median_salary_hour=df['salary_hour_avg'].median()

In [7]:
df_filled=df

In [8]:
df_filled['salary_year_avg']=df_filled['salary_year_avg'].fillna(median_salary_year)
df_filled['salary_hour_avg']=df_filled['salary_hour_avg'].fillna(median_salary_hour)

In [11]:
df_filled.loc[:,['salary_year_avg','salary_hour_avg']]

        salary_year_avg  salary_hour_avg
0              115000.0            45.98
1              115000.0            45.98
2              115000.0            45.98
3              115000.0            45.98
4              115000.0            45.98
...                 ...              ...
785736         115000.0            45.98
785737         115000.0            45.98
785738         115000.0            45.98
785739         115000.0            45.98
785740         115000.0            45.98

[785741 rows x 2 columns]

In [12]:
df_unique=df_filled

In [15]:
df_unique=df_unique.drop_duplicates()
print('Length before drop duplicates:',len(df_filled))
print('Length after drop duplicates:',len(df_unique))
print('Number of duplicates:',len(df_filled)-len(df_unique))

Length before drop duplicates: 785741
Length after drop duplicates: 785640
Number of duplicates: 101

In [16]:
df_unique_1=df_filled.drop_duplicates(subset=['job_title','company_name'])
print('Length before drop duplicates:',len(df_filled))
print('Length after drop duplicates:',len(df_unique_1))
print('Number of duplicates:',len(df_filled)-len(df_unique_1))
print('Number of duplicates:',len(df_unique)-len(df_unique_1))

Length before drop duplicates: 785741
Length after drop duplicates: 508042
Number of duplicates: 277699
Number of duplicates: 277598

salary_rate
year     22004
hour     10662
month      382
week        10
day          9
Name: count, dtype: int64